import { Box, Center, VStack } from "@chakra-ui/react";
import { Footer } from "./components/footer";
import ReactMarkdown from "react-markdown";
import { Header } from "./components/header";

export function TermsOfService() {
  return (
    <Center>
      <VStack>
        <Box maxWidth="48em" padding="2em" minHeight="85vh">
          <Header />
          <ReactMarkdown>
            {`# Terms of Service for Lil Pitch

**Effective Date:** 16th November 2025

Welcome to Lil Pitch ("we," "us," or "our"). By accessing or using our website and AI agent service (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.

---

### 1. Use of the Service

Lil Pitch provides an AI agent to help you practice your startup pitch. You may use the Service for its intended purpose only.

* You must be at least 13 years old to use the Service.
* You agree not to use the Service for any illegal or unauthorized purpose.
* You agree not to misuse the Service, such as by attempting to gain unauthorized access to our systems, introducing malicious code, or using the Service to generate harmful, hateful, or harassing content.

---

### 2. User-Provided Content

To use the Service, you provide textual context (e.g., your role, interviewer persona) and engage in a voice call.

* **Contextual Information:** You grant us a temporary, non-exclusive license to use the text context you provide solely to configure and operate the AI agent for your session. This information is not stored after your session.
* **Voice Transcripts:** Your voice is processed to create transcripts, which are stored as described in our Privacy Policy. By using the Service, you grant us a worldwide, non-exclusive, royalty-free license to use, store, and process these transcripts to provide, maintain, and improve the Service.
* **Ownership:** You retain any intellectual property rights you have in the content you create. We claim no ownership over your pitch or the ideas within it.

---

### 3. Disclaimers

The Service is provided on an "as-is" and "as-available" basis.

* **No Guarantees:** We do not warrant that the Service will be uninterrupted, error-free, or secure.
* **AI Output:** The AI agent is a tool for practice. The responses, feedback, and "interviewer" persona are generated by an AI. **This is not professional coaching or advice.** We make no guarantees about the accuracy, relevance, or quality of the AI's output. Any decisions you make based on the AI's feedback are your own.
* **No Confidentiality:** Do not provide any highly sensitive or confidential information (e.g., trade secrets, non-public financial information) during your practice sessions. While we have privacy measures in place (as described in our Privacy Policy), we cannot guarantee absolute confidentiality for the data processed by our third-party AI partners.

---

### 4. Limitation of Liability

To the fullest extent permitted by law, Lil Pitch and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from:

* (a) your access to or use of or inability to access or use the Service;
* (b) any conduct or content of any third party on the Service;
* (c) any content obtained from the Service.

---

### 5. Changes to These Terms

We reserve the right to modify these Terms at any time. If we make changes, we will post the revised Terms on this page and update the "Effective Date" at the top. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.

---

### 6. Contact Us

If you have any questions about these Terms, please contact us at:

**elias@brickwiseai.com**`}
          </ReactMarkdown>
        </Box>
        <Footer />
      </VStack>
    </Center>
  );
}
